# Generated by Django 4.2 on 2024-05-22 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_category_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
